### ISSUE TITLE
Crash when opening a new conversation for non-buddies with the Window Merge plugin active and no conversations open

### ISSUE THREAD

**Issue by syldrathecat** [fcwill/fchat-pidgin#100]
Pidgin crashes when opening a new conversation with someone not on your buddy list, while no conversation windows are open other than the dummy Window Merge conversation tab (seen here: https://files.catbox.moe/48ocyx.png). Ways of opening a conversation in this way are at least:

* Using the "New Instant Message" option on the buddy list window
* Receiving a private message from someone

Pidgin and Window Merge plugins are the latest versions in Debian Unstable as of writing (Pidgin 2.10.11 with Window Merge 0.3).

This doesn't seem to happen when opening conversations on other services (e.g. IRC), if the person contacting you is on your buddy list, or if a real conversation window is open.

Backtrace:
```
Program received signal SIGSEGV, Segmentation fault.

#0  0x00005555555b52ad in generate_send_to_items (win=0x555556334d60)
    at /build/pidgin-itbiVH/pidgin-2.10.11/./pidgin/gtkconv.c:3895
#1  0x00005555555bcab8 in pidgin_conv_update_fields (conv=0x555555aaeeb0,
    fields=(PIDGIN_CONV_BUDDY_ICON | PIDGIN_CONV_TAB_ICON | PIDGIN_CONV_COLORIZE_TITLE))
    at /build/pidgin-itbiVH/pidgin-2.10.11/./pidgin/gtkconv.c:6741
#2  0x00005555555bd54c in update_buddy_status_changed (buddy=<optimized out>, old=0x5555565e8aa0, newstatus=0x0)
    at /build/pidgin-itbiVH/pidgin-2.10.11/./pidgin/gtkconv.c:7624
#3  0x00007ffff5242fd0 in purple_signal_emit_vargs (instance=<optimized out>,
    signal=signal@entry=0x7ffff528eadd "buddy-signed-on", args=args@entry=0x7fffffffb9d0)
    at /build/pidgin-itbiVH/pidgin-2.10.11/./libpurple/signals.c:482
#4  0x00007ffff524312e in purple_signal_emit (instance=<optimized out>,
    signal=signal@entry=0x7ffff528eadd "buddy-signed-on")
    at /build/pidgin-itbiVH/pidgin-2.10.11/./libpurple/signals.c:434
#5  0x00007ffff52013f9 in purple_blist_update_buddy_status (buddy=0x5555565e8270, old_status=0x5555565e8aa0)
    at /build/pidgin-itbiVH/pidgin-2.10.11/./libpurple/blist.c:919
#6  0x00007ffff523b068 in purple_prpl_got_user_status (account=account@entry=0x55555595d730,
    name=name@entry=0x55555634f480 "Syldra Kitty", status_id=0x7fffe09b1baa "online")
    at /build/pidgin-itbiVH/pidgin-2.10.11/./libpurple/prpl.c:284
#7  0x00007fffe09a8037 in flist_update_friend (pc=<optimized out>, name=0x55555634f480 "Syldra Kitty",
    update_icon=1, new_buddy=<optimized out>) at f-list_commands.c:33
#8  0x00007ffff5242fd0 in purple_signal_emit_vargs (instance=<optimized out>,
    signal=signal@entry=0x7ffff5293019 "conversation-created", args=args@entry=0x7fffffffbca0)
    at /build/pidgin-itbiVH/pidgin-2.10.11/./libpurple/signals.c:482
#9  0x00007ffff524312e in purple_signal_emit (instance=<optimized out>,
    signal=signal@entry=0x7ffff5293019 "conversation-created")
    at /build/pidgin-itbiVH/pidgin-2.10.11/./libpurple/signals.c:434
#10 0x00007ffff5211b1e in purple_conversation_new (type=type@entry=PURPLE_CONV_TYPE_IM,
    account=account@entry=0x55555595d730, name=name@entry=0x5555564e7790 "Syldra Kitty")
    at /build/pidgin-itbiVH/pidgin-2.10.11/./libpurple/conversation.c:452
#11 0x00007ffff5241bc1 in serv_got_im (gc=gc@entry=0x555556319ba0, who=who@entry=0x555556537be0 "Syldra Kitty",
    msg=msg@entry=0x5555565413b0 "hello!", flags=flags@entry=PURPLE_MESSAGE_RECV, mtime=1459116698)
    at /build/pidgin-itbiVH/pidgin-2.10.11/./libpurple/server.c:624
#12 0x00007fffe09a3626 in flist_process_PRI (pc=0x555556319ba0, root=<optimized out>) at f-list_callbacks.c:670
#13 0x00007fffe09aa4dc in flist_dispatch (
    message=message@entry=0x5555564a0930 "PRI {\"character\":\"Syldra Kitty\",\"recipient\":\"SyldraTheCat\",\"message\":\"hello!\"}", len=len@entry=78, fla=0x55555634f030, fla=0x55555634f030) at f-list_connection.c:204
#14 0x00007fffe09aab75 in flist_process_hybi_frame (payload_len=78,
    payload=0x5555564a0930 "PRI {\"character\":\"Syldra Kitty\",\"recipient\":\"SyldraTheCat\",\"message\":\"hello!\"}", opcode=1 '\001', is_final=1, fla=0x55555634f030) at f-list_connection.c:226
#15 flist_process_hybi (fla=<optimized out>) at f-list_connection.c:330
#16 flist_process_real (fla=0x55555634f030) at f-list_connection.c:381
#17 0x00005555555c591e in pidgin_io_invoke (source=<optimized out>, condition=<optimized out>,
    data=0x55555595fce0) at /build/pidgin-itbiVH/pidgin-2.10.11/./pidgin/gtkeventloop.c:73
#18 0x00007ffff5537fea in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007ffff5538390 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007ffff55386b2 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007ffff67df5b7 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#22 0x000055555558bf37 in main (argc=2, argv=0x7fffffffe498)
    at /build/pidgin-itbiVH/pidgin-2.10.11/./pidgin/gtkmain.c:937
```

**Comment by syldrathecat** [comment]
Assuming this is a mostly unavoidable problem with the window merge plugin as I can trigger similar crashes consistently in other ways using different protocols.
